feature_groups:
  base_v1:
    features:
      - market.close.v1
      - market.amount.v1
      - market.ret_5d_rank.v1
      - limit.high_stop.v1
      - moneyflow.net_mf_amount_rank.v1

  price_volume_exp_v1:
    features:
      - market.ret_20d_rank.v1
      - market.reversal_1d_rank.v1
      - risk.volatility_20d_rank.v1
      - liquidity.amount_ratio_5d_rank.v1
      - market.close_position_20d_rank.v1

  base_plus_price_volume_v1:
    features:
      - market.close.v1
      - market.amount.v1
      - market.ret_5d_rank.v1
      - limit.high_stop.v1
      - moneyflow.net_mf_amount_rank.v1
      - market.ret_20d_rank.v1
      - market.reversal_1d_rank.v1
      - risk.volatility_20d_rank.v1
      - liquidity.amount_ratio_5d_rank.v1
      - market.close_position_20d_rank.v1
